---
functional:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизации через Github
  - Возможность выбора языка программирования в терминале баттла
  - Возможность просмотра истории баттлов
  - Возможность просмотра баттла зрителям в режиме online
  - Возможность переподключения участника к баттлу
  - Возможность просмотра повтора баттла
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Участник не может писать и изменять код соперника
  - Зрители не могут писать код и вносить изменения в код участников
  - Пользователи не могут вносить изменения в таблицу лидеров вручную
  - Участники не могут вносить изменения в предустановленную задачу баттла
